#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : eventviews
Version  : 18.08.0
Release  : 2
URL      : https://download.kde.org/stable/applications/18.08.0/src/eventviews-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/eventviews-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/eventviews-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: eventviews-lib
Requires: eventviews-license
Requires: eventviews-data
Requires: eventviews-locales
BuildRequires : akonadi-calendar-dev
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : calendarsupport-dev
BuildRequires : kcalcore-dev
BuildRequires : kcalutils-dev
BuildRequires : kcontacts-dev
BuildRequires : kdiagram-dev
BuildRequires : kholidays-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libkdepim-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package data
Summary: data components for the eventviews package.
Group: Data

%description data
data components for the eventviews package.


%package dev
Summary: dev components for the eventviews package.
Group: Development
Requires: eventviews-lib
Requires: eventviews-data
Provides: eventviews-devel

%description dev
dev components for the eventviews package.


%package lib
Summary: lib components for the eventviews package.
Group: Libraries
Requires: eventviews-data
Requires: eventviews-license

%description lib
lib components for the eventviews package.


%package license
Summary: license components for the eventviews package.
Group: Default

%description license
license components for the eventviews package.


%package locales
Summary: locales components for the eventviews package.
Group: Default

%description locales
locales components for the eventviews package.


%prep
%setup -q -n eventviews-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535425473
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535425473
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/eventviews
cp COPYING %{buildroot}/usr/share/doc/eventviews/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/eventviews/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libeventviews

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservicetypes5/calendardecoration.desktop
/usr/share/xdg/eventviews.categories
/usr/share/xdg/eventviews.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/EventViews/AgendaView
/usr/include/KF5/EventViews/CalendarDecoration
/usr/include/KF5/EventViews/ConfigDialogInterface
/usr/include/KF5/EventViews/EventView
/usr/include/KF5/EventViews/Helper
/usr/include/KF5/EventViews/JournalView
/usr/include/KF5/EventViews/ListView
/usr/include/KF5/EventViews/MonthView
/usr/include/KF5/EventViews/MultiAgendaView
/usr/include/KF5/EventViews/Prefs
/usr/include/KF5/EventViews/TimeLineView
/usr/include/KF5/EventViews/TodoView
/usr/include/KF5/EventViews/ViewCalendar
/usr/include/KF5/EventViews/WhatsNextView
/usr/include/KF5/EventViews/eventview.h
/usr/include/KF5/EventViews/helper.h
/usr/include/KF5/EventViews/prefs.h
/usr/include/KF5/eventviews/EventView
/usr/include/KF5/eventviews/Helper
/usr/include/KF5/eventviews/Prefs
/usr/include/KF5/eventviews/agendaview.h
/usr/include/KF5/eventviews/calendardecoration.h
/usr/include/KF5/eventviews/configdialoginterface.h
/usr/include/KF5/eventviews/eventview.h
/usr/include/KF5/eventviews/eventviews_export.h
/usr/include/KF5/eventviews/helper.h
/usr/include/KF5/eventviews/journalview.h
/usr/include/KF5/eventviews/listview.h
/usr/include/KF5/eventviews/monthview.h
/usr/include/KF5/eventviews/multiagendaview.h
/usr/include/KF5/eventviews/prefs.h
/usr/include/KF5/eventviews/timelineview.h
/usr/include/KF5/eventviews/todoview.h
/usr/include/KF5/eventviews/viewcalendar.h
/usr/include/KF5/eventviews/whatsnextview.h
/usr/include/KF5/eventviews_version.h
/usr/lib64/cmake/KF5EventViews/KF5EventViewsConfig.cmake
/usr/lib64/cmake/KF5EventViews/KF5EventViewsConfigVersion.cmake
/usr/lib64/cmake/KF5EventViews/KF5EventViewsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5EventViews/KF5EventViewsTargets.cmake
/usr/lib64/libKF5EventViews.so
/usr/lib64/qt5/mkspecs/modules/qt_EventViews.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5EventViews.so.5
/usr/lib64/libKF5EventViews.so.5.9.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/eventviews/COPYING
/usr/share/doc/eventviews/COPYING.LIB

%files locales -f libeventviews.lang
%defattr(-,root,root,-)

